### ISSUE TITLE
Caused a non-recoverable error

### ISSUE THREAD

**Issue by ArseniyKruglov** [Klonan/Repair_Turret#7] opened 2022-10-18 20:14 UTC
It worked ok for a few hours, but started to crush when huge attacks began.

![image](https://user-images.githubusercontent.com/56249652/196534252-2a1d5ab4-541e-4647-8cb2-b4970c1e2f6c.png)

![image](https://user-images.githubusercontent.com/56249652/196534433-19afb765-66c5-478e-b55b-f1648dd7f4ad.png)

**Comment by Klonan** [comment] 2022-12-16 09:04
Can you provide a save game?

**Comment by ArseniyKruglov** [comment] 2023-01-06 17:04
[Save](https://drive.google.com/file/d/1xL7B-6W27xJZ63wedYatq23SH_fVGlsG/view?usp=share_link)

It also seems that removing repair packs from personal logistics solves the problem.

**Comment by Klonan** [comment] 2023-01-24 11:48
I couldn't reproduce it, but I see in the code how it could happen, so it should be fixed

**Closed by Klonan** 2023-01-24 11:48 UTC
